name: affogato_core
description: AffogatoCore is the powerhouse behind the AffogatoEditor, which provides an intuitive and feature-rich code editing experience in Flutter.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.3

# Add regular dependencies here.
dependencies:

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
